//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20/05/2021 16:33:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace mainModel
{
    [Serializable()]
    public partial class City {

        public City()
        {
            OnCreated();
        }

        public virtual long Id { get; set; }

        public virtual string CityName { get; set; }

        public virtual long? Weather { get; set; }

        public virtual string CityKey { get; set; }

        public virtual DateTime? WeatherDate { get; set; }

        public virtual TimeSpan? WeatherTime { get; set; }

        public virtual string WeatherText { get; set; }

        public virtual Favorite Favorite { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
